version: "3.8"

services:
  db:
    image: mariadb:10.7.3
    container_name: mariadb
    environment:
      MYSQL_DATABASE: school
      MYSQL_USER: principal
      MYSQL_PASSWORD: secret
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    restart: always

  website:
    container_name: crudapp
    build:
      context: .
    environment:
      - MYSQL_DBHOST=db
      - MYSQL_DBPORT=3306
      - MYSQL_DBUSER=principal
      - MYSQL_DBPASS=secret
      # - MYSQL_DBNAME=school
    ports:
      - 8080:80
      - 8083:443
      # - 80:80
      # - 443:443
    depends_on:
      - db

volumes:
  crudapp:
  db: